### ISSUE TITLE
Scoped Resource?

### ISSUE THREAD

**Issue by halsten** [tandasat/RemoteWriteMonitor#2]
Any good explanation on the reason behind using this? I think it's over bloating the code and not to mention the Driver as well. I, personally, didn't find anything unique for using it. Maybe I missed something?

**Comment by tandasat** [comment]
It is used as an alternative to std::unique_ptr. IIRC, std::unique_ptr is not available on WDK (for drivers), and I want to have something handy RAII classes which relatively reliable in terms of quality. Because it was one of proposals for the C++ standard, I concluded that it was relatively good quality and worth adapting it.

Just recently, I found that it required some extra configuration to compile it with VS2015 + WDK for Win10 and was problematic on that environment, but otherwise I personally see value to use it, or I do not see any strong reasons not to use it (assuming that it is not production code and okay to use C++ for driver development).

**Comment by halsten** [comment]
It required additional settings on VS2013 as well. But, I see your point. Though, it's not strongly advised to use such approach. I just thought for the purpose of the example it overly complicated the source. Maybe would make people who want to start learning demotivate a little bit. But, it doesn't bother me much. Just wanted to know your reasons. Thank you! :)

**Comment by tandasat** [comment]
No problem. Also, you have gotten a point; it is not very friendly for code readers. It is for writers for sure.

I will also check out if you need an additional settings with VS2013 as I thought I committed a change for this on VS2013. It may have been filtered out, perhaps because it was in a user.filter file.

Thanks for comments anyway.

**Comment by tandasat** [comment]
Closed as a replacement ticket #3 was issued. I was going to check if ScopedResource compiles in VS2013, but the project cannot be loaded with 2013 and fix was going to be a bigger change than I thought. Rather than fixing it for 2013, I am going to completely switch to VS2015 ( #3 ) and drop cover for VS2013.

**Comment by halsten** [comment]
Agreed, its your right to move to a newer version, though not everyone will have VS2015. I don't think it should be problematic or stand in the way of someone who wants to compile the project. At least to the person who knows what he/she is doing or dealing with. But, thanks for addressing all issues and handling all tickets.
